// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTu49GZOJbYrMrxfzFFXL-sQp4VjSzx1E',
    appId: '1:580039527184:web:a62bae064a4149b7343395',
    messagingSenderId: '580039527184',
    projectId: 'studyplanner-e7b3b',
    authDomain: 'studyplanner-e7b3b.firebaseapp.com',
    storageBucket: 'studyplanner-e7b3b.firebasestorage.app',
    measurementId: 'G-JNS01PKLJN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCv8ZmWwHer5j-YIaQfCo0ov19cjVuqFys',
    appId: '1:580039527184:android:8f2dd9a0f75140d9343395',
    messagingSenderId: '580039527184',
    projectId: 'studyplanner-e7b3b',
    storageBucket: 'studyplanner-e7b3b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyACG8Yhz0Ne8esfKd1y3_sMPs4hY7fGGgI',
    appId: '1:580039527184:ios:f43536488497c4ce343395',
    messagingSenderId: '580039527184',
    projectId: 'studyplanner-e7b3b',
    storageBucket: 'studyplanner-e7b3b.firebasestorage.app',
    iosBundleId: 'com.example.studyplanner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyACG8Yhz0Ne8esfKd1y3_sMPs4hY7fGGgI',
    appId: '1:580039527184:ios:f43536488497c4ce343395',
    messagingSenderId: '580039527184',
    projectId: 'studyplanner-e7b3b',
    storageBucket: 'studyplanner-e7b3b.firebasestorage.app',
    iosBundleId: 'com.example.studyplanner',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTu49GZOJbYrMrxfzFFXL-sQp4VjSzx1E',
    appId: '1:580039527184:web:a11af2fb72b76ed3343395',
    messagingSenderId: '580039527184',
    projectId: 'studyplanner-e7b3b',
    authDomain: 'studyplanner-e7b3b.firebaseapp.com',
    storageBucket: 'studyplanner-e7b3b.firebasestorage.app',
    measurementId: 'G-MTHNKW2HTC',
  );
}
